ht.Default.setImage("basic", {
  width: 133,
  height: 140,
  comps: [
    {
      type: "roundRect",
      rect: [0, 0, 130, 15],
      borderWidth: 1,
      borderColor: "black",
      background: "grey",
    },
    {
      type: "rect",
      rect: [15, 15, 100, 110],
      borderWidth: 1,
      borderColor: "black",
      background: "grey",
    },
    {
      type: "circle",
      rect: [25, 90, 21, 21],
      borderWidth: 3,
      borderColor: "#ffffff",
      background: { func: "style@colorCircle" },
    },
    {
      type: "rect",
      rect: [60, 25, 20, 90],
      borderWidth: 2,
      borderColor: "black",
      background: "black",
    },
    {
      type: "rect",
      rect: [60, 25, 20, 90],
      borderWidth: 2,
      borderColor: "black",
      background: "#00eaff",
      clipPercentage: { func: "attr@pro", value: 17 / 100 },
    },
    {
      type: "roundRect",
      rect: [0, 125, 130, 15],
      borderWidth: 1,
      borderColor: "black",
      background: "grey",
    },
    {
      type: "shape",
      borderWidth: 2,
      borderColor: "black",
      background: "black",
      points: [
        85,
        25,
        105,
        25,

        85,
        95 / 2,
        95,
        95 / 2,

        85,
        70,
        105,
        70,

        85,
        185 / 2,
        95,
        185 / 2,

        85,
        115,
        105,
        115,
      ],
      segments: [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 5],
    },
    {
      type: "text",
      text: { func: "style@bottomText" },
      rect: [36, 135, 60, 70],
      align: "center",
      color: "black",
      font: "bold 20px Arial",
    },
  ],
});
